openapi: 3.0.4
info:
  title: DNS Lookup
  description: DNS Lookup is a simple tool for looking up the DNS records of a domain. It returns the A, MX, and other records of the domain.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/dnslookup:
    get:
      summary: Lookup DNS
      description: DNS Lookup is a simple tool for looking up the DNS records of a domain. It returns the A, MX, and other records of the domain.
      operationId: dnslookup
      parameters:
      - name: domain
        in: query
        schema:
          type: string
        required: true
        description: The domain name for which you want to lookup the DNS records. Do not include the protocol, and not subdomains (e.g., myspace.com)
        example: myspace.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  domain: myspace.com
                  records:
                    A:
                    - 34.111.176.156
                    NS:
                    - ns-cloud-a1.googledomains.com
                    - ns-cloud-a3.googledomains.com
                    - ns-cloud-a4.googledomains.com
                    - ns-cloud-a2.googledomains.com
                    SOA:
                      nsname: ns-cloud-a1.googledomains.com
                      hostmaster: cloud-dns-hostmaster.google.com
                      serial: 2
                      refresh: 21600
                      retry: 3600
                      expire: 259200
                      minttl: 300
                    MX:
                    - exchange: us-smtp-inbound-1.mimecast.com
                      priority: 10
                    - exchange: us-smtp-inbound-2.mimecast.com
                      priority: 10
                    TXT:
                    - - al4upe6q5cl13sg4srvfivflvg
                    - - oZ19a+EOIwWVDPJ7POj14UAGBfzk9xcJMmsTUAMUy7H82sDuVCxvw9rZqdg3znFrdTH04+49zd1djhEAt0ooiA==
                    - - qpdYoeakhlmAxsnmxgAVFmJgUSibqb/y+Eu6GGn8pdmLf+mFGIB3jhRAxIC5KObsPMES9MW2c+oOrpOo/lCQVw==
                    - - google-site-verification=q0iWqpcfOBclAJaCeWh83v62QQ4uCgbWObQ08p37qgU
                    - - cr40m536tje9on1slld9bi81bg
                    - - cj65vjpq0s1v9u7vfo020c6rel
                    - - google-site-verification=eu-3gW1JePvsGRRCaEvH17YUOTFJNofm4lnz2Pk0LTc
                    - - MS=ms89904786
                    - - 'v=spf1 mx ip4:63.208.226.34 ip4:204.16.32.0/22 ip4:67.134.143.0/24 ip4:216.205.243.0/24 ip4:34.85.156.5/32 ip4:35.245.108.108/32 ip4:34.86.129.193/32 ip4:34.86.134.94/32 '
                      - 'ip4:34.85.222.234/32 ip4:34.86.176.234/32 ip4:34.86.125.212/32 ip4:34.85.224.60/32 ip4:34.86.160.49/32 ip4:35.245.64.166/32 ip4:35.188.226.11/32 '
                      - 'ip4:34.86.208.228/32 ip4:34.85.216.144/32 ip4:35.221.22.153/32 ip4:34.86.137.108/32 ip4:34.86.51.35/32 ip4:34.150.221.40/32 ip4:34.85.216.70/32 ip4:34.86.37.191/32 ip4:34.85.214.215/32 '
                      - ip4:35.236.234.82/32 ip4:34.86.161.241/32 ip4:216.32.181.16 ip4:216.178.32.0/20 ip4:168.235.224.0/24 include:_netblocks.mimecast.com -all
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
