name: apiverve_dnslookup
description: DNS Lookup is a simple tool for looking up the DNS records of a domain. It returns the A, MX, and other records of the domain.
version: 1.1.14
homepage: https://dnslookup.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/dnslookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
